### ISSUE TITLE
migrations fail when not using atlas

### ISSUE THREAD

**Issue by miltontony** [praekelt/jmbo#33]
using `jmbo==1.2.0`
```
Running migrations for jmbo:
 - Migrating forwards to 0009_auto__del_unique_modelbase_slug.
 > jmbo:0004_auto__add_field_modelbase_location
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/migrators.py", line 106, in run
    south.db.db.current_orm = self.orm(migration)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/migrators.py", line 281, in orm
    return migration.orm()
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/migration/base.py", line 443, in orm
    return FakeORM(self.migration_class(), self.app_label())
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/orm.py", line 48, in FakeORM
    _orm_cache[args] = _FakeORM(*args)  
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/orm.py", line 127, in __init__
    self.models[name] = self.make_model(app_label, model_name, data)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/orm.py", line 324, in make_model
    field = self.eval_in_context(code, app, extra_imports)
  File "/home/tonym/work/mobileweb/ve/local/lib/python2.7/site-packages/south/orm.py", line 235, in eval_in_context
    raise ValueError("Cannot import the required field '%s'" % value)
ValueError: Cannot import the required field 'atlas.fields.CoordinateField'
```

**Comment by hedleyroos** [comment]
Fixed in jmbo-2.
